"""empty message

Revision ID: 27a3696cc0be
Revises: fa58db3973b5
Create Date: 2020-07-05 20:49:39.862102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a3696cc0be'
down_revision = 'fa58db3973b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actors', sa.Column('image_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actors', 'image_path')
    # ### end Alembic commands ###
