"""empty message

Revision ID: f7f0c8b1ec7d
Revises: 27a3696cc0be
Create Date: 2020-07-05 20:56:41.380109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f0c8b1ec7d'
down_revision = '27a3696cc0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actors', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actors', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
