"""empty message

Revision ID: fa58db3973b5
Revises: 
Create Date: 2020-07-03 22:32:49.960130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa58db3973b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('movie_status', sa.Enum('Directing', 'Filming', 'Published', 'ReadyToPublish', 'Recruting', 'Review', name='moviestatus'), nullable=False),
    sa.Column('movie_category', sa.Enum('Action', 'Adveture', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'History', 'Horror', 'Musical', 'Romance', 'SciFi', name='moviescategory'), nullable=False),
    sa.Column('movie_rating', sa.Enum('G', 'PG', 'PG13', 'R', name='moviesrating'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MovieActors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovieActors')
    op.drop_table('Movies')
    op.drop_table('Actors')
    # ### end Alembic commands ###
